"""add forecast_models table

Revision ID: 3c2ed3cdd656
Revises: f1ea88d5d715
Create Date: 2026-08-16 03:05:44.446917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3c2ed3cdd656'
down_revision: Union[str, None] = 'f1ea88d5d715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_models',
    sa.Column('microgrid_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.Enum('DEMAND', 'SOLAR_GENERATION', name='forecast_target'), nullable=False),
    sa.Column('dataset_source', postgresql.ENUM('SIMULATED', 'HARDWARE', name='telemetry_source', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('TRAINED', 'FAILED', name='forecast_model_status'), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('algorithm_rationale', sa.String(length=2000), nullable=False),
    sa.Column('feature_set', sa.JSON(), nullable=False),
    sa.Column('training_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('n_train', sa.Integer(), nullable=False),
    sa.Column('n_validation', sa.Integer(), nullable=False),
    sa.Column('n_test', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('model_path', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['microgrid_id'], ['microgrids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_models_microgrid_id'), 'forecast_models', ['microgrid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_models_microgrid_id'), table_name='forecast_models')
    op.drop_table('forecast_models')
    # ### end Alembic commands ###
