"""add decisions table

Revision ID: 4323ba37038e
Revises: 3c2ed3cdd656
Create Date: 2026-08-19 06:49:59.463413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4323ba37038e'
down_revision: Union[str, None] = '3c2ed3cdd656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('microgrid_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('source', postgresql.ENUM('SIMULATED', 'HARDWARE', name='telemetry_source', create_type=False), nullable=False),
    sa.Column('optimization_status', sa.Enum('OPTIMAL', 'INFEASIBLE', 'SAFE_FALLBACK', 'ERROR', name='optimization_status'), nullable=False),
    sa.Column('horizon_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('recommended_battery_action', sa.Enum('CHARGE', 'DISCHARGE', 'IDLE', name='battery_action'), nullable=False),
    sa.Column('recommended_battery_power_w', sa.Float(), nullable=True),
    sa.Column('load_recommendations', sa.JSON(), nullable=False),
    sa.Column('expected_grid_import_wh', sa.Float(), nullable=True),
    sa.Column('expected_grid_export_wh', sa.Float(), nullable=True),
    sa.Column('expected_renewable_utilization_pct', sa.Float(), nullable=True),
    sa.Column('expected_peak_w', sa.Float(), nullable=True),
    sa.Column('constraints_checked', sa.JSON(), nullable=False),
    sa.Column('constraints_satisfied', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.String(length=4000), nullable=False),
    sa.Column('recommendation_reason', sa.String(length=4000), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.String(length=2000), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['microgrid_id'], ['microgrids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_created_at'), 'decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_decisions_microgrid_id'), 'decisions', ['microgrid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_microgrid_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_created_at'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
