"""energy balance consistency: battery_power_w and telemetry integrity constraints

Revision ID: f1ea88d5d715
Revises: fab6fb5b8636
Create Date: 2026-08-13 07:39:33.953737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ea88d5d715'
down_revision: Union[str, None] = 'fab6fb5b8636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_device_readings_device_recorded_source', 'device_readings', ['device_id', 'recorded_at', 'source'])
    op.add_column('energy_readings', sa.Column('battery_power_w', sa.Float(), nullable=True))
    op.create_unique_constraint('uq_energy_readings_microgrid_recorded_source', 'energy_readings', ['microgrid_id', 'recorded_at', 'source'])
    # ### end Alembic commands ###

    # Manually added: alembic autogenerate does not detect CheckConstraint
    # changes, so these are written explicitly to match the ORM models in
    # app/models/telemetry.py.
    op.create_check_constraint(
        'ck_energy_readings_consumption_non_negative', 'energy_readings', 'consumption_w >= 0'
    )
    op.create_check_constraint(
        'ck_energy_readings_generation_non_negative', 'energy_readings', 'generation_w >= 0'
    )
    op.create_check_constraint(
        'ck_energy_readings_grid_import_non_negative', 'energy_readings', 'grid_import_w >= 0'
    )
    op.create_check_constraint(
        'ck_energy_readings_grid_export_non_negative', 'energy_readings', 'grid_export_w >= 0'
    )
    op.create_check_constraint(
        'ck_energy_readings_available_energy_non_negative', 'energy_readings', 'available_energy_w >= 0'
    )
    op.create_check_constraint(
        'ck_energy_readings_battery_soc_range',
        'energy_readings',
        'battery_soc_percent IS NULL OR (battery_soc_percent >= 0 AND battery_soc_percent <= 100)',
    )
    op.create_check_constraint('ck_device_readings_power_non_negative', 'device_readings', 'power_w >= 0')
    op.create_check_constraint('ck_device_readings_voltage_non_negative', 'device_readings', 'voltage_v >= 0')
    op.create_check_constraint('ck_device_readings_current_non_negative', 'device_readings', 'current_a >= 0')


def downgrade() -> None:
    op.drop_constraint('ck_device_readings_current_non_negative', 'device_readings', type_='check')
    op.drop_constraint('ck_device_readings_voltage_non_negative', 'device_readings', type_='check')
    op.drop_constraint('ck_device_readings_power_non_negative', 'device_readings', type_='check')
    op.drop_constraint('ck_energy_readings_battery_soc_range', 'energy_readings', type_='check')
    op.drop_constraint('ck_energy_readings_available_energy_non_negative', 'energy_readings', type_='check')
    op.drop_constraint('ck_energy_readings_grid_export_non_negative', 'energy_readings', type_='check')
    op.drop_constraint('ck_energy_readings_grid_import_non_negative', 'energy_readings', type_='check')
    op.drop_constraint('ck_energy_readings_generation_non_negative', 'energy_readings', type_='check')
    op.drop_constraint('ck_energy_readings_consumption_non_negative', 'energy_readings', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_energy_readings_microgrid_recorded_source', 'energy_readings', type_='unique')
    op.drop_column('energy_readings', 'battery_power_w')
    op.drop_constraint('uq_device_readings_device_recorded_source', 'device_readings', type_='unique')
    # ### end Alembic commands ###
