"""add hardware environmental telemetry

Revision ID: f6fd024c7ae8
Revises: f8e02fc1a614
Create Date: 2026-09-17 12:10:54.005254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fd024c7ae8'
down_revision: Union[str, None] = 'f8e02fc1a614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_readings', sa.Column('temperature_c', sa.Float(), nullable=True))
    op.add_column('device_readings', sa.Column('humidity_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_readings', 'humidity_percent')
    op.drop_column('device_readings', 'temperature_c')
    # ### end Alembic commands ###
