"""add telemetry tables

Revision ID: fab6fb5b8636
Revises: e886b6516c26
Create Date: 2026-08-13 07:25:09.314499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fab6fb5b8636'
down_revision: Union[str, None] = 'e886b6516c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_readings',
    sa.Column('microgrid_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumption_w', sa.Float(), nullable=False),
    sa.Column('generation_w', sa.Float(), nullable=False),
    sa.Column('grid_import_w', sa.Float(), nullable=False),
    sa.Column('grid_export_w', sa.Float(), nullable=False),
    sa.Column('available_energy_w', sa.Float(), nullable=False),
    sa.Column('battery_soc_percent', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'HARDWARE', name='telemetry_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['microgrid_id'], ['microgrids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_readings_microgrid_id'), 'energy_readings', ['microgrid_id'], unique=False)
    op.create_index('ix_energy_readings_microgrid_recorded_at', 'energy_readings', ['microgrid_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_energy_readings_recorded_at'), 'energy_readings', ['recorded_at'], unique=False)
    op.create_table('device_readings',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('power_w', sa.Float(), nullable=False),
    sa.Column('voltage_v', sa.Float(), nullable=False),
    sa.Column('current_a', sa.Float(), nullable=False),
    sa.Column('status', postgresql.ENUM('ONLINE', 'OFFLINE', 'FAULT', 'DECOMMISSIONED', name='device_status', create_type=False), nullable=False),
    sa.Column('source', sa.Enum('SIMULATED', 'HARDWARE', name='telemetry_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_readings_device_id'), 'device_readings', ['device_id'], unique=False)
    op.create_index('ix_device_readings_device_recorded_at', 'device_readings', ['device_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_device_readings_recorded_at'), 'device_readings', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_readings_recorded_at'), table_name='device_readings')
    op.drop_index('ix_device_readings_device_recorded_at', table_name='device_readings')
    op.drop_index(op.f('ix_device_readings_device_id'), table_name='device_readings')
    op.drop_table('device_readings')
    op.drop_index(op.f('ix_energy_readings_recorded_at'), table_name='energy_readings')
    op.drop_index('ix_energy_readings_microgrid_recorded_at', table_name='energy_readings')
    op.drop_index(op.f('ix_energy_readings_microgrid_id'), table_name='energy_readings')
    op.drop_table('energy_readings')
    # ### end Alembic commands ###
